### ISSUE TITLE
Staking page for Whale Token

### ISSUE THREAD

**Issue by 0xFable** [White-Whale-Defi-Platform/white-whale-frontend#151]
<img width="112" alt="image" src="https://user-images.githubusercontent.com/86927513/212683498-75a0ae09-e343-40f7-9b23-60afa4d39f1b.png">

We need a new page on the frontend for Staking the CW20 Token. Designs in figma which are under construction. 
Will be under a `Governance` navbar title 

Smart contracts specced.

**Comment by Sen-Com** [comment]
Moved to different issues & PR #172
