### ISSUE TITLE
[BUG] Injective Config File is missing

### ISSUE THREAD

**Issue by silvermind** [White-Whale-Defi-Platform/white-whale-frontend#283]
https://app.whitewhale.money/injective/pools is (404 on console) broken as the config file at https://app.whitewhale.money/mainnet/injective-1/config.json does not exist. (maybe by design as the Dashboard is not enabled yet..

The Injective Config should be here: https://github.com/White-Whale-Defi-Platform/white-whale-frontend/blob/main/public/mainnet/injective-1/config.json

similar to e.g.
Juno Sample: https://github.com/White-Whale-Defi-Platform/white-whale-frontend/blob/main/public/mainnet/juno-1/config.json

---

seems to be loaded from here: https://github.com/White-Whale-Defi-Platform/white-whale-frontend/blob/main/components/Pages/Dashboard/hooks/useDashboardData.ts#L43

**Comment by worrex** [comment]
yes, it is due due to fact that it is not enabled yet, should not cause any problems. But thanks for reporting anyways!
