### ISSUE TITLE
Fix Injective Swap / update endpoints

### ISSUE THREAD

**Issue by nick134-bit** [White-Whale-Defi-Platform/white-whale-frontend#332]
Grpc and rest endpoints throw **503** errors.

---

## Steps to Reproduce

1. Navigate to `injective/swap` page and insert value
2. Stuck on loading

---

### Additional context

Add any other context about the problem here, code snippets, json responses and so on.

<details>
<summary>Screen shots</summary>

</details>

<details>
  <summary>Logs</summary>

```

```

</details>

**Comment by KaliaNetwork** [comment]
Hello @nick134-bit, could you check again, and share the last result with us.

**Comment by nick134-bit** [comment]
Hey @KaliaNetwork, looks like this has been resolved.
