### ISSUE TITLE
feat(navbar): add arrows

### ISSUE THREAD

**Issue by Sen-Com** [White-Whale-Defi-Platform/white-whale-frontend#340]
Add arrows to the drop down menus and also indicate that bridge is an outgoing link via a little icon

![telegram-cloud-photo-size-1-5114308067096374850-y](https://github.com/White-Whale-Defi-Platform/white-whale-frontend/assets/86837735/14f61b62-af98-44f0-aa28-c577438aa2e1)

**Comment by nick134-bit** [comment]
![image](https://github.com/White-Whale-Defi-Platform/white-whale-frontend/assets/76399455/e2119183-8754-40a9-9fdb-17d0f4a0520a)
something like this ?
