### ISSUE TITLE
Mobile feature testing

### ISSUE THREAD

**Issue by 0xFable** [White-Whale-Defi-Platform/white-whale-frontend#363]
We want to test: 

+ [ ] Mobile connections via wallet connect (cosmosstation, keplr, etc)
+ [ ] Swapping both direct pair and via router 
+ [ ] Provide liquidity 
+ [ ] Withdraw 
+ [ ] Vaults, deposit withdraw 
+ [ ] Change to a chain with 18 decimal tokens and do swaps, provides etc

**Comment by pinventado** [comment]
Any particular chain you are testing? I can test a couple of these but, how to provide details and results of the test?
