### ISSUE TITLE
Implement a start test framework to start the push for frontend coverage

### ISSUE THREAD

**Issue by 0xFable** [White-Whale-Defi-Platform/white-whale-frontend#61]
As of right now, there are no automated tests in any capacity. This is a huge area of opportunity to reduce errors making their way to production but getting the frontend to some reasonable % coverage level is a big undertaking to be broken into steps. Before we can get there we need a nice initial test setup that we can depend on over time to avoid redefining testing methods and techniques all over the place. 
We need fixtures, mocks and other things which we can have in one place and build up that location over time such that all tests are using common code from this one place. This will make it easier to deal with fundamental changes at any level and when needed we can handle very specific cases in the tests themselves. 

For this task we just want an initial setup, ideally something both at the Unit testing and Integration testing level either is fine for a starting point. Afterwards in other issues we will build this up but cant do that until we have a starting point.

**Comment by Sen-Com** [comment]
@0xFable this is part of the refactoring project, feel free to reopen then :)
