### ISSUE TITLE
Integration testing for frontend

### ISSUE THREAD

**Issue by 0xFable** [White-Whale-Defi-Platform/white-whale-frontend#65]
The frontend is in need of some nice integration testing suite of tests. 
In order to build this up similar to #61 we need some proper test runner/suite/so on. 

There are alot of potential options now, we have seen in the wild people running integration test scenarios against :
+ a locally spun up or remote local terra to do on demand chain interactions.
+ `ts-relayer` for testing chain to chain interactions and possibly can be used for the above 

We need to get some base in place with which all further tests can import as integration testing setup is a big affair for a new dev to figure out, this individual needs alot of piping plumbing ready to go and documented so they can then focus on the testing case.

**Comment by Sen-Com** [comment]
@0xFable this is part of the refactoring project, feel free to reopen then :)
