### ISSUE TITLE
Deployment to both Netlify as well as another provider such as Akash

### ISSUE THREAD

**Issue by 0xFable** [White-Whale-Defi-Platform/white-whale-frontend#69]
To make this work we need to setup a separate CI/CD pipeline within out pipeline sort of. I am trying to put as much information here as I can as when I was exploring this I found very little. 
For Akash deployments to work in github actions we will use this action https://github.com/ovrclk/akash-ghaction-setup either directly from CI or by defining our own `akash` action based on the above. 

With the action to help we now we two jobs for this pipeline which depends on each other. The first the image generation which will be pushed to a container registry and then second a deployment to akash Job. 

Some things to note: 
+ The very first deployment most likely is always manual to get the DSEQ and SSH Certs and all that for the secrets 
+ The wallet where deployments happen must be prefunded in some means to do things 
+ On each new push to main we want to update the akash deployment with a newly built image

**Comment by Sen-Com** [comment]
@0xFable this is part of the refactoring project, feel free to reopen then :)
